In [1]:
import numpy as np
import scipy.linalg

In [18]:
z = np.random.normal(loc=0.5, scale=0.05, size=(2, 2))
im = np.random.normal(loc=0.5, scale=0.05, size=(2, 2))
z = z + im*1j
print z

[[ 0.40593042+0.53913577j  0.49310762+0.45040684j]
 [ 0.49794128+0.50544739j  0.46576143+0.55265431j]]


In [19]:
def test_uni(x):
    return abs(np.dot(x, x.conj().T))

In [20]:
print test_uni(z)

[[ 0.90146833  0.95322423]
 [ 0.95322423  1.02578309]]


In [21]:
def make_unitary(x):
    q, r = scipy.linalg.qr(z)
    d = r.diagonal()
    x_u = q * d/abs(d)
    return x_u, q, r

In [22]:
z_u, q, r = make_unitary(z)
print z_u
print abs(z_u)

[[ 0.41454516+0.55057743j  0.50058515-0.52386192j]
 [ 0.50850870+0.51617411j -0.40610834+0.55682961j]]
[[ 0.68919025  0.72458043]
 [ 0.72458043  0.68919025]]


In [23]:
for y in z_u:
    print np.sum(map(lambda x: abs(x)**2, y))
for y in z_u.T:
    print np.sum(map(lambda x: abs(x)**2, y))
print test_uni(z_u)

1.0
1.0
1.0
1.0
[[  1.00000000e+00   2.28036972e-16]
 [  2.28036972e-16   1.00000000e+00]]


In [17]:
print q, '\n'
print r, '\n'
print abs(q), '\n'
print abs(r), '\n'

[[-0.54168806-0.49414802j  0.20106567+0.64958785j]
 [-0.52174718-0.43608676j -0.24694065-0.6903829j ]] 

[[-0.98688160+0.j         -0.99197891-0.01011679j]
 [ 0.00000000+0.j         -0.04999857+0.j        ]] 

[[ 0.73321772  0.67999395]
 [ 0.67999395  0.73321772]] 

[[ 0.9868816   0.9920305 ]
 [ 0.          0.04999857]] 



In [24]:
print q, '\n'
print r, '\n'
print abs(q), '\n'
print abs(r), '\n'

[[-0.41454516-0.55057743j  0.50058515-0.52386192j]
 [-0.50850870-0.51617411j -0.40610834+0.55682961j]] 

[[-0.97921881+0.j         -0.97450880+0.04416442j]
 [ 0.00000000+0.j          0.12947604+0.j        ]] 

[[ 0.68919025  0.72458043]
 [ 0.72458043  0.68919025]] 

[[ 0.97921881  0.97550905]
 [ 0.          0.12947604]] 

