In [13]:
import numpy as np
import neutrinocommon.physconst.physicsconstants as PC
from neutrinocommon.neu import neuosc

In [14]:
pc = PC.PhysicsConstants()

In [17]:
def deg_to_rad(x):
    return x / 180. * np.pi

In [32]:
pc.th12 = deg_to_rad(33.56)
pc.th23 = deg_to_rad(41.6)
pc.th13 = deg_to_rad(8.46)
pc.deltaCP = 261

pc.numneu = 4
pc.th14 = deg_to_rad(40)
pc.th24 = deg_to_rad(20)
pc.th34 = deg_to_rad(20)
pc.dm41sq = 1e-2

pc.Refresh()

In [33]:
mm = neuosc.MixMatrix(pc)
print mm.U

[[  6.31404475e-01+0.j           4.18869039e-01+0.j
   -5.75152614e-13-0.11269962j   6.42787610e-01+0.j        ]
 [ -5.69665851e-01-0.07648554j   4.65354587e-01-0.05073994j
    6.17097936e-01+0.03234355j   2.62002630e-01+0.j        ]
 [  2.22970095e-01-0.07662643j  -7.05744670e-01-0.0508334j
    6.18234603e-01+0.030393j     2.46201938e-01+0.j        ]
 [ -4.60504009e-01+0.05751481j  -3.21409278e-01+0.0381549j
   -4.64038940e-01+0.08350407j   6.76434266e-01+0.j        ]]


In [34]:
print mm.U.shape
print abs(mm.U)
print abs(np.dot(mm.U, mm.U.conj().T))

(4, 4)
[[ 0.63140448  0.41886904  0.11269962  0.64278761]
 [ 0.57477754  0.46811263  0.61794496  0.26200263]
 [ 0.23576953  0.70757302  0.61898123  0.24620194]
 [ 0.46408178  0.32366606  0.47149238  0.67643427]]
[[  1.00000000e+00   5.56194658e-17   1.38777878e-17   5.56194658e-17]
 [  5.56194658e-17   1.00000000e+00   1.67110694e-16   3.26162902e-17]
 [  1.38777878e-17   1.67110694e-16   1.00000000e+00   5.55111512e-17]
 [  5.56194658e-17   3.20601351e-17   5.55111512e-17   1.00000000e+00]]
