In [1]:
import numpy as np
import scipy.linalg

In [2]:
mod_u = np.array([[0.82, 0.55, 0.15], [0.38, 0.54, 0.75], [0.41, 0.63, 0.64]])
print mod_u

[[ 0.82  0.55  0.15]
 [ 0.38  0.54  0.75]
 [ 0.41  0.63  0.64]]


In [3]:
def test_uni(x):
    return abs(np.dot(x, x.conj().T))

In [4]:
print test_uni(mod_u)

[[ 0.9974  0.7211  0.7787]
 [ 0.7211  0.9985  0.976 ]
 [ 0.7787  0.976   0.9746]]


In [5]:
nuni = 0.9

In [6]:
z = []
for y in mod_u:
    z += [x for x in y]
    z.append(np.sqrt(nuni + 0*1j - np.sum(map(lambda x: x**2, y))))
for y in mod_u.T:
    z.append(np.sqrt(nuni + 0*1j - np.sum(map(lambda x: x**2, y))))
z.append(np.sqrt(nuni - (z[12]**2 + z[13]**2 + z[14]**2)))
z = np.array(z).reshape(4, 4)

In [7]:
def make_unitary(x):
    q, r = scipy.linalg.qr(z)
    d = r.diagonal()
    q *= d/abs(d)
    return q

In [8]:
z_u = make_unitary(z)
print z_u
print abs(z_u)

[[ 0.79279802-0.j         -0.57786057+0.j         -0.09590712+0.j
   0.00000000+0.16837545j]
 [ 0.36739420+0.j          0.48683180-0.j          0.71256582+0.j
   0.00000000+0.34679425j]
 [ 0.39639901+0.j          0.65063399-0.j         -0.64771701+0.j
   0.00000000-0.00243085j]
 [ 0.00000000+0.28171018j  0.00000000+0.07581147j  0.00000000+0.25202072j
   0.92270122+0.j        ]]
[[ 0.79279802  0.57786057  0.09590712  0.16837545]
 [ 0.3673942   0.4868318   0.71256582  0.34679425]
 [ 0.39639901  0.65063399  0.64771701  0.00243085]
 [ 0.28171018  0.07581147  0.25202072  0.92270122]]


In [9]:
for y in z_u:
    print np.sum(map(lambda x: abs(x)**2, y))
for y in z_u.T:
    print np.sum(map(lambda x: abs(x)**2, y))
print test_uni(z_u)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
[[  1.00000000e+00   1.38777878e-17   1.39862080e-17   0.00000000e+00]
 [  1.38777878e-17   1.00000000e+00   2.38524478e-18   5.55111512e-17]
 [  1.39862080e-17   2.38524478e-18   1.00000000e+00   5.85469173e-17]
 [  0.00000000e+00   5.55111512e-17   5.85469173e-17   1.00000000e+00]]


In [10]:
for y in z_u[:-1, :-1]:
    print np.sum(map(lambda x: abs(x)**2, y))
for y in z_u[:-1, :-1].T:
    print np.sum(map(lambda x: abs(x)**2, y))
print test_uni(z_u[:-1, :-1])

0.971649707734
0.879733748536
0.999994090947
0.920639371845
0.994252620688
0.936485554683
[[  9.71649708e-01   5.83916379e-02   4.09296201e-04]
 [  5.83916379e-02   8.79733749e-01   8.43006320e-04]
 [  4.09296201e-04   8.43006320e-04   9.99994091e-01]]
